#!/bin/bash

set -eu -o pipefail

file="${1}"
shift
target="${1}"
shift

[[ -d "${HOME}/.gnupg" ]] || mkdir "${HOME}/.gnupg"

if [[ -f "${file}" ]] && [[ -d "$(dirname "${target}")" ]]; then
  gpg2 --no-keyring --no-auto-key-locate --no-auto-key-retrieve --no-default-keyring --yes --output "${target}" --decrypt "${file}"
fi

# source and export all secret variables
set -a
source "${target}"
set +a

exec "$@"
